// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20180606101220_AddedVerlag")]
    partial class AddedVerlag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Erscheinungsdatum");

                    b.Property<int>("SeitenAnzahl");

                    b.Property<string>("Sprache");

                    b.Property<string>("Titel");

                    b.Property<int?>("VerlagId");

                    b.HasKey("Id");

                    b.HasIndex("VerlagId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("WebApplication1.Models.Verlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Verlag");
                });

            modelBuilder.Entity("WebApplication1.Models.Book", b =>
                {
                    b.HasOne("WebApplication1.Models.Verlag", "Verlag")
                        .WithMany("Books")
                        .HasForeignKey("VerlagId");
                });
#pragma warning restore 612, 618
        }
    }
}
